### ISSUE TITLE
Can't connect to rtorrent web interface

### ISSUE THREAD

**Issue by akizzle** [jbbodart/arch-rtorrentvpn#1]
Only log entries:
017-03-15 01:33:37	stdout	2017-03-15 02:33:37,866 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-03-15 01:33:37	stdout	2017-03-15 02:33:37,821 CRIT Set uid to user 0

I add all the commands you have and see the folders populate but can't connect to IP:8080

Any help would be greatly appreciated.

**Comment by jbbodart** [comment]
Yes these log entries are expected.
Did you build the container yourself or did you pull the image from the docker repo ?
Can you tell which processes are running inside the container ?

The complete log file is /config/rtorrentvpn.log. Could you post it in order to debug the issue ?

**Comment by jbbodart** [comment]
Cannot reproduce
