### ISSUE TITLE
Change rtorrent running userid

### ISSUE THREAD

**Issue by BadFlo** [jbbodart/arch-rtorrentvpn#2]
Hi,
Any change to be able to force puid and pgid running rtorrent and nginx processes for better rights management on ?

**Comment by jbbodart** [comment]
Hello,

Sorry, I do not maintain this repo anymore. I should specify it in the README.
I made similar docker image (alpine based) which supports PUID and PGID settings for rtorrent : https://github.com/jbbodart/alpine-rtorrentvpn

**Comment by BadFlo** [comment]
Nice, tanks for the link.
Put it also in the Readme 😉
